name: Deploy to QA

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the tag to deploy"
        required: true
        type: string

jobs:

  prepare:
    name: Prepare Deployment
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Set deployment tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ inputs.tag }}"
          else
            TAG="${{ github.sha }}"
          fi

          echo "Deployment tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"


  deploy-qa:
    name: Deploy to QA
    needs: prepare
    runs-on: ubuntu-latest

    environment:
      name: qa-approval

    steps:
      - name: Approved - Deploy to QA
        run: |
          echo "================================="
          echo "✅ QA APPROVAL RECEIVED"
          echo "================================="
          echo "Deploying: ${{ needs.prepare.outputs.tag }}"
          echo "🚀 Deploying to QA..."

      - name: Deployment completed
        run: |
          echo "✅ Deployment completed successfully."
